name: Create GitHub Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Create tarball
        run: tar -czf dist.tar.gz -C dist .

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          TAG=${{ github.ref_name }}
          gh release create $TAG --title "Release $TAG" --notes "Automated release for $TAG" dist.tar.gz
